--- Register customer andre
INSERT INTO PUBLIC.BLC_CUSTOMER (CUSTOMER_ID,CREATED_BY,DATE_CREATED,DATE_UPDATED,UPDATED_BY,CHALLENGE_ANSWER,DEACTIVATED,EMAIL_ADDRESS,FIRST_NAME,IS_TAX_EXEMPT,LAST_NAME,PASSWORD,PASSWORD_CHANGE_REQUIRED,IS_PREVIEW,RECEIVE_EMAIL,IS_REGISTERED,TAX_EXEMPTION_CODE,USER_NAME,CHALLENGE_QUESTION_ID,LOCALE_CODE) VALUES (100,100,'2018-07-12 09:06:22.085','2018-07-12 09:06:22.085',100,NULL,false,'andre@tenneshop.com','andre',false,'steve','tenneshop',false,NULL,true,true,NULL,'andre@tenneshop.com',NULL,NULL);

INSERT INTO PUBLIC.HC_CUSTOMER (NUM_SAUCES_BOUGHT,TOTAL_HEAT_RATING,CUSTOMER_ID) VALUES (0,0,100);

INSERT INTO PUBLIC.BLC_CUSTOMER_ROLE (CUSTOMER_ROLE_ID,CUSTOMER_ID,ROLE_ID) VALUES (1,100,1);

INSERT INTO PUBLIC.BLC_EMAIL_TRACKING (EMAIL_TRACKING_ID,DATE_SENT,EMAIL_ADDRESS,"TYPE") VALUES (1,'2018-07-12 09:06:22.136','andre@tenneshop.com',NULL);

INSERT INTO PUBLIC.BLC_CUSTOMER_ATTRIBUTE (CUSTOMER_ATTR_ID,NAME,"VALUE",CUSTOMER_ID) VALUES (1,'referralCode','',100);
--- End register customer andre

--- Register customer meiliang
INSERT INTO PUBLIC.BLC_CUSTOMER (CUSTOMER_ID,CREATED_BY,DATE_CREATED,DATE_UPDATED,UPDATED_BY,CHALLENGE_ANSWER,DEACTIVATED,EMAIL_ADDRESS,FIRST_NAME,IS_TAX_EXEMPT,LAST_NAME,PASSWORD,PASSWORD_CHANGE_REQUIRED,IS_PREVIEW,RECEIVE_EMAIL,IS_REGISTERED,TAX_EXEMPTION_CODE,USER_NAME,CHALLENGE_QUESTION_ID,LOCALE_CODE) VALUES (101,100,'2018-07-12 09:06:22.085','2018-07-12 09:06:22.085',100,NULL,false,'dongmeilianghy@sina.com','meiliang',false,'dong','tenneshop',false,NULL,true,true,NULL,'dongmeilianghy@sina.com',NULL,NULL);

INSERT INTO PUBLIC.HC_CUSTOMER (NUM_SAUCES_BOUGHT,TOTAL_HEAT_RATING,CUSTOMER_ID) VALUES (0,0,101);

INSERT INTO PUBLIC.BLC_CUSTOMER_ROLE (CUSTOMER_ROLE_ID,CUSTOMER_ID,ROLE_ID) VALUES (2,101,1);

INSERT INTO PUBLIC.BLC_EMAIL_TRACKING (EMAIL_TRACKING_ID,DATE_SENT,EMAIL_ADDRESS,"TYPE") VALUES (2,'2018-07-12 09:06:22.136','dongmeilianghy@sina.com',NULL);

INSERT INTO PUBLIC.BLC_CUSTOMER_ATTRIBUTE (CUSTOMER_ATTR_ID,NAME,"VALUE",CUSTOMER_ID) VALUES (2,'referralCode','',101);
--- End register customer meiliang